version: '2'

services:
  hbase-master:
    image: blueskyareahm/hbase-base:2.1.3
    command: master
    networks:
      - mynetwork
    ports:
      - 16000:16000
      - 16010:16010
      - 16020:16020
    environment:
      - HBASE_MANAGES_ZK=false

  hbase-regionserver:
    image: blueskyareahm/hbase-base:2.1.3
    command: regionserver
    networks:
      - mynetwork
    ports:
      - 16030:16030
      - 16201:16201
      - 16301:16301
    environment:
      - HBASE_MANAGES_ZK=false

  zookeeper:
    image: blueskyareahm/hbase-zookeeper:3.4.13
    networks:
      - mynetwork
    ports:
      - 2181:2181

networks:
  mynetwork:
    driver: bridge